apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-app
  template:
    metadata:
      labels:
        app: svc-app
    spec:
      containers:
        - name: app
          image: xxx.dkr.ecr.xxx.amazonaws.com/dualstack:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: myawscred
