apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: <AWS_ACCOUNT_ID>.dkr.ecr.eu-west-2.amazonaws.com/dualstack
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: newest-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/jazzzyjeff/serverless-vs-kubernetes
    targetRevision: HEAD
    path: kubernetes/app/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
