apiVersion: apps/v1
kind: Deployment
metadata:
  name: svk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svk-app
  template:
    metadata:
      labels:
        app: svk-app
    spec:
      containers:
        - name: app
          image: 052275556902.dkr.ecr.eu-west-2.amazonaws.com/dualstack:latest
          ports:
            - containerPort: 8000
