---
serviceAccount:
  name: argocd-image-updater

authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      aws ecr --region eu-west-2 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

config:
  registries:
  - name: ECR
    api_url: https://052275556902.dkr.ecr.eu-west-2.amazonaws.com
    prefix: 052275556902.dkr.ecr.eu-west-2.amazonaws.com
    ping: yes
    insecure: no
    credentials: ext:/scripts/auth.sh
    credsexpire: 10h