on:
  workflow_dispatch:
    inputs:
      operation:
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - destroy
      stack:
        required: true
        type: choice
        options:
          - kubernetes
          - serverless

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.stack }}
          path: ${{ github.event.inputs.stack }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ github.event.inputs.stack }}
          path: ${{ github.event.inputs.stack }}

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: app
          path: app

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: frontend
          path: frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: github-actions

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Get Backend Parameter
        run: |
          BACKEND=$(aws ssm get-parameter \
            --name "/backend" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          echo "BACKEND=$BACKEND" >> $GITHUB_ENV

      - uses: qetza/replacetokens-action@v1
        with:
          sources: |
            variables.auto.tfvars.tmpl => variables.auto.tfvars
            backend.tf.tmpl => backend.tf
          variables: >
            [
              ${{ toJSON(vars) }},
              ${{ toJSON(secrets) }},
              { "SERVICE": "dualstack-${{ github.event.inputs.stack }}" },
              { "BACKEND": "${{ env.BACKEND }}" }
            ]
          token-pattern: custom
          token-prefix: '${'
          token-suffix: '}'
          log-level: debug
          no-telemetry: true
          root: ${{ github.event.inputs.stack }}/terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.stack }}/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ github.event.inputs.stack }}/terraform

      - name: Terraform Apply
        if: |
          github.event_name != 'workflow_dispatch' ||
          github.event.inputs.operation == 'deploy'
        run: terraform apply -auto-approve
        working-directory: ${{ github.event.inputs.stack }}/terraform

      - name: Terraform Destroy
        if: |
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.operation == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ github.event.inputs.stack }}/terraform
